### ISSUE TITLE
Provide Option to Clear Output Terminal after every run

### ISSUE THREAD

**Issue by Jeyanthinath** [formulahendry/vscode-code-runner#144]
It would be better if you guys provide option to clear output terminal after every code run

**Comment by formulahendry** [comment]
I think below setting is what you want:
```
"code-runner.clearPreviousOutput": true
```

**Comment by Jeyanthinath** [comment]
you guys are really awesome :+1:

**Comment by homeahmed2012** [comment]
but this is not working if you set "code-runner.runInTerminal": true 
I want it to run command like this: 
clear && .....the rest of the command

**Comment by formulahendry** [comment]
@homeahmed2012 , please open a separate issue for this.

**Comment by formulahendry** [comment]
@homeahmed2012 , #152 is created to track this.

**Comment by formulahendry** [comment]
@homeahmed2012 , this issue has been fixed. Please try the latest version

**Comment by Ejaz-Hussain** [comment]
> 
> 
> @homeahmed2012 , this issue has been fixed. Please try the latest version

i did try the latest version but the matter is same. still have the issue

**Comment by coderraseed** [comment]
Same Issue Does not work

**Comment by coderraseed** [comment]
Now work
When You write this code
"code-runner.runInTerminal": false,

**Comment by diproyf87** [comment]
@coderraseed hey buddy thanks a lot. I insanely tried every way but it didn't work till I followed your suggestion.

**Comment by rrsouzza** [comment]
> I think below setting is what you want:
> 
> ```
> "code-runner.clearPreviousOutput": true
> ```

Just added this in my global .vscode settings and it worked perfectly. At least with typescript, which I'm currently running.
