### ISSUE TITLE
Clear previous output when running in terminal

### ISSUE THREAD

**Issue by formulahendry** [formulahendry/vscode-code-runner#152]
Address https://github.com/formulahendry/vscode-code-runner/issues/144#issuecomment-318676057

**Comment by formulahendry** [comment]
Fixed in v0.6.30

**Comment by diproyf87** [comment]
@formulahendry I am still encountering the issue, it doesn't clear my previous c/c++ output after every run. please help!!

**Comment by CatNofishing** [comment]
Does not work until now  in python, i can not believe this isssue exists so long time

**Comment by sagun-basnet** [comment]
clear previous output for c/c++ is not working please fix it.

**Comment by Farhan9599** [comment]
I am also facing the same even after enabling the option of clear output screen before each run in code runner extension in vs code.
Kindly help me to resolve the issue.

**Comment by Prem-17** [comment]
its 2024 and this issue is not yet resolved
