### ISSUE TITLE
[Bug][VS Code 1.56] Not detect shell on Windows correctly 

### ISSUE THREAD

**Issue by officer** [formulahendry/vscode-code-runner#783]
- VS Code Version: 1.56.0
- OS Version:  Windows_NT x64 10.0 19042
- Code Runner Version: v0.11.3

**Describe the bug**
When we assign "Command Prompt" to "terminal.integrated.defaultProfile.windows" parameter, "&&" in code-runner.executorMap will be translated into "; if ($?) { <command > } style which is not working on Command Prompt.

**To Reproduce**

1. Configure "terminal.integrated.defaultProfile.windows": "Command Prompt" in settings.json
2.  Include "&&" in any of language "code-runner.executorMap".
3.  Run the code.

**Actual behavior**
Translate "&& <command>" into "; if ($?) { <command> }"

**Expected behavior**
Interpret "&&" as is.

**Screenshots**

**Comment by officer** [comment]
Probably it's a visual studio code side issue, but anyway I post it at here now.

**Comment by blackpancake** [comment]
I also found this problem. However, I found a temporary solution to this problem:

add `"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe"` in `settings.json` to make **CodeRunner** not translate `&` into `; if ($?) { }`.

However, this will cause a warning in `settings.json`. I guess this may be because **CodeRunner**  doesn't realize that vscode has **abandoned** the `"terminal.integrated.shell.windows"` setting.

![image](https://user-images.githubusercontent.com/62934143/117560407-04088580-b07d-11eb-87f2-bbc4ab4ee631.png)

**Comment by formulahendry** [comment]
Related issues:

- https://github.com/microsoft/vscode-python/issues/16175
- https://github.com/microsoft/vscode/issues/121760

**Comment by formulahendry** [comment]
@officer @blackpancake  This issue has been fixed. Please install the latest version and have a try.

**Comment by jack20951948** [comment]
![image](https://user-images.githubusercontent.com/56648560/118354795-77d7f000-b59f-11eb-8ae5-7899e2f11ee7.png)

still have issue with bash....

**Comment by blackpancake** [comment]
> ![image](https://user-images.githubusercontent.com/56648560/118354795-77d7f000-b59f-11eb-8ae5-7899e2f11ee7.png)
> 
> still have issue with bash....

In CMD, this issue has been fixed.
![image](https://user-images.githubusercontent.com/62934143/118356406-a4224b00-b564-11eb-89be-2f7787491eb3.png)

**Comment by formulahendry** [comment]
@jack20951948 You could use below setting:
```
"code-runner.terminalRoot": "/"
```

**Comment by jack20951948** [comment]
> @jack20951948 You could use below setting:
> 
> ```
> "code-runner.terminalRoot": "/"
> ```

![image](https://user-images.githubusercontent.com/56648560/118386020-ba083c80-b646-11eb-9294-78c3e335f06a.png)
yeah...I've already had this setting...

**Comment by jack20951948** [comment]
seems in git bash still have some issues

**Comment by sangnovamoqapi** [comment]
This worked for me.
![code_runner_issue_for_bash](https://user-images.githubusercontent.com/56693923/120108382-94208300-c182-11eb-88bd-b1095ef5314c.jpg)
